<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\ReadMe assets\**" />
    <EmbeddedResource Remove="Resources\ReadMe assets\**" />
    <None Remove="Resources\ReadMe assets\**" />
    <Page Remove="Resources\ReadMe assets\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\app.ico" />
    <None Remove="Resources\Images\DefaultBanner.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\LilitaOne-Regular.ttf" />
    <Resource Include="Resources\app.ico" />
    <Resource Include="Resources\Images\DefaultBanner.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Images\settingsIcon.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Config\" />
    <Folder Include="Scripts\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ValveKeyValue" Version="0.70.0.499" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

</Project>
